$('.replyDelete').click((e)=>{
    let rno=  $(e.target).attr('ref');
    if(confirm('정말삭제하시겠습니까?')){
        $.ajax({
            url:"replyDelete",
            type:'post',
            data:{rno:rno},
            success:(result)=>{
                if(result>0){
                    alert("댓글삭제성공")
                    location.reload()
                }else{
                    alert("댓글삭제실패")
                }
            },
            error:(e)=>{console.log(e)}
        })
    }
})